spring:
  application:
    name: application-service
  mvc:
    servlet:
      path: /application-service # // localhost:8111/application-service/application-service

server:
  port: 8111

eureka:
  instance:
    hostname: localhost
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka

